export const LOAD_DIRECTORY = 'LOAD_DIRECTORY';
export const FETCH_MOVIES_INFO = 'FETCH_MOVIES_INFO';

export const FETCH_MOVIES_REQUEST = 'FETCH_MOVIES_REQUEST';
export const FETCH_MOVIES_FAILURE = 'FETCH_MOVIES_FAILURE';
export const FETCH_MOVIES_SUCCESS = 'FETCH_MOVIES_SUCCESS';

export const SEARCH_MOVIES_SUCCESS = 'SEARCH_MOVIES_SUCCESS';
