// export const LOAD_DIRECTORY = 'LOAD_DIRECTORY';
// export const FETCH_MOVIES_INFO = 'FETCH_MOVIES_INFO';
//
// export const FETCH_MOVIES_REQUEST = 'FETCH_MOVIES_REQUEST';
// export const FETCH_MOVIES_FAILURE = 'FETCH_MOVIES_FAILURE';
// export const FETCH_MOVIES_SUCCESS = 'FETCH_MOVIES_SUCCESS';

export const LOAD_LOCAL_DATA = 'LOAD_LOCAL_DATA';
export const LOAD_MOVIE_INFO_FROM_LOCAL = 'LOAD_MOVIE_INFO_FROM_LOCAL';

// 搜索douban电影
export const SEARCH_MOVIES_REQUEST = 'SEARCH_MOVIES_REQUEST';
export const SEARCH_MOVIES_SUCCESS = 'SEARCH_MOVIES_SUCCESS';
export const SEARCH_MOVIES_FAILURE = 'SEARCH_MOVIES_FAILURE';
